-- Supabase schema for the Round 2 HR & People Ops system of record.
-- Apply to the existing Round 1 Supabase project before live seeding. Table names intentionally
-- preserve the source-system casing used by Auto and the reseeding loader.

create table if not exists "Workers" (
  "Worker_WID" text primary key,
  "Employee_ID" text unique,
  "Legal_Name" text,
  "Preferred_Name" text,
  "Business_Title" text,
  "Job_Profile" text,
  "Job_Family" text,
  "Management_Level" text,
  "Position_ID" text,
  "Manager_Name" text,
  "Manager_WID" text,
  "Cost_Center" text,
  "Location" text,
  "Hire_Date" date,
  "Worker_Type" text,
  "Time_Type" text,
  "FTE" numeric,
  "Email_Work" text,
  "jurisdiction" text,
  "time_zone" text,
  "work_auth_expiry" date,
  "cohort" text
);

-- `create table if not exists` does not add fields to an existing Round 1 table.
alter table "Workers" add column if not exists "jurisdiction" text;
alter table "Workers" add column if not exists "time_zone" text;
alter table "Workers" add column if not exists "work_auth_expiry" date;
alter table "Workers" add column if not exists "cohort" text;

create table if not exists "Manager_Directory" (
  "Manager_WID" text primary key,
  "Employee_ID" text,
  "Name" text,
  "Email_Work" text,
  "Org" text
);

create table if not exists "policy_config" (
  "field_key" text primary key,
  "category" text,
  "value" text,
  "justification" text
);

create table if not exists "Onboarding_Tasks" (
  "Event_ID" text primary key,
  "Employee_ID" text,
  "Business_Process" text,
  "Step_Name" text,
  "Milestone" text,
  "Due_Date" date,
  "Status" text,
  "Completed_Date" date,
  "Assigned_To_Role" text
);

create table if not exists "Provisioning_Integration" (
  "Integration_Event_ID" text primary key,
  "Employee_ID" text,
  "Resource" text,
  "Requested_On" date,
  "Status" text,
  "Fulfilled_On" date
);

create table if not exists "Peakon_Engagement" (
  "Response_ID" text primary key,
  "Employee_ID" text,
  "Survey_Round" text,
  "Milestone" text,
  "Driver" text,
  "Score" numeric,
  "Comment" text,
  "Submitted_At" date,
  "sentiment" text,
  "x_confidential" boolean not null default false,
  "manager_response_days" numeric
);

alter table "Peakon_Engagement" add column if not exists "sentiment" text;
alter table "Peakon_Engagement" add column if not exists "x_confidential" boolean not null default false;
alter table "Peakon_Engagement" add column if not exists "manager_response_days" numeric;

create table if not exists "Locations_Entities" (
  "entity_id" text primary key,
  "name" text,
  "country" text,
  "jurisdiction" text,
  "timezone" text
);

create table if not exists "Compliance_Items" (
  "item_id" text primary key,
  "employee_id" text,
  "doc_type" text,
  "jurisdiction" text,
  "due_date" date,
  "status" text
);

create table if not exists "Payroll_Records" (
  "payroll_id" text primary key,
  "employee_id" text,
  "cycle" text,
  "gross" numeric,
  "net" numeric,
  "status" text,
  "error_reason" text
);

create table if not exists "Learning_Milestones" (
  "milestone_id" text primary key,
  "employee_id" text,
  "course" text,
  "due_day" text,
  "status" text
);

create table if not exists "Attrition_History" (
  "record_id" text primary key,
  "job_family" text,
  "tenure_days" numeric,
  "left_flag" boolean,
  "reason" text
);

create table if not exists "Cross_Team_Dependencies" (
  "dep_id" text primary key,
  "employee_id" text,
  "team" text,
  "task" text,
  "status" text,
  "blocks_day_one" boolean not null default false
);

-- Sanitized, Auto-written audit trail. Never write a raw sensitive disclosure here.
create table if not exists "Cases_Audit_Log" (
  "case_id" text primary key,
  "timestamp" timestamptz,
  "employee_id" text,
  "case_type" text,
  "channel" text,
  "policy_rules_fired" text,
  "outcome" text
);

-- Command Center operational records. IDs are generated by the calling workflow/API so they are
-- portable across Auto and FastAPI; these tables must only contain sanitized metadata.
create table if not exists "policy_versions" (
  "version_id" text primary key,
  "created_at" timestamptz not null default now(),
  "created_by" text,
  "config_snapshot" jsonb not null,
  "change_summary" text
);

create table if not exists "policy_evaluations" (
  "evaluation_id" text primary key,
  "evaluated_at" timestamptz not null default now(),
  "execution_id" text,
  "employee_id" text,
  "policy_version_id" text,
  "policy_key" text not null,
  "outcome" text not null,
  "action" text,
  "evidence" jsonb not null default '{}'::jsonb
);

create table if not exists "workflow_events" (
  "event_id" text primary key,
  "occurred_at" timestamptz not null default now(),
  "execution_id" text,
  "employee_id" text,
  "cohort" text,
  "operator_id" text,
  "event_type" text not null,
  "status" text not null,
  "reason_codes" jsonb not null default '[]'::jsonb,
  "details" jsonb not null default '{}'::jsonb
);

create table if not exists "workbench_cases" (
  "case_id" text primary key,
  "created_at" timestamptz not null default now(),
  "employee_id" text,
  "case_type" text not null,
  "priority" text not null,
  "status" text not null default 'open',
  "recommended_action" text,
  "sanitized_context" jsonb not null default '{}'::jsonb,
  "assigned_to" text,
  "resolved_at" timestamptz
);

-- This table deliberately stores only a secure reference and minimum routing metadata. Raw pulse
-- comments must remain in the restricted Auto/Supabase confidential path, never a dashboard payload.
create table if not exists "Confidential_Cases" (
  "case_id" text primary key,
  "created_at" timestamptz not null default now(),
  "employee_id" text,
  "status" text not null default 'open',
  "secure_reference" text not null,
  "assigned_role" text not null default 'people_ops_confidential',
  "resolved_at" timestamptz
);

create table if not exists "case_resolutions" (
  "resolution_id" text primary key,
  "case_id" text not null,
  "resolved_at" timestamptz not null default now(),
  "resolved_by" text not null,
  "decision" text not null,
  "sanitized_feedback" text
);

create table if not exists "integration_health" (
  "integration_key" text primary key,
  "category" text not null,
  "status" text not null,
  "checked_at" timestamptz not null default now(),
  "last_success_at" timestamptz,
  "detail" text
);

create table if not exists "reconciliation_leases" (
  "lease_key" text primary key,
  "lease_owner" text not null,
  "lease_until" timestamptz not null,
  "updated_at" timestamptz not null default now()
);

create index if not exists workers_cohort_idx on "Workers" ("cohort");
create index if not exists onboarding_tasks_employee_idx on "Onboarding_Tasks" ("Employee_ID");
create index if not exists provisioning_employee_idx on "Provisioning_Integration" ("Employee_ID");
create index if not exists peakon_employee_idx on "Peakon_Engagement" ("Employee_ID");
create index if not exists compliance_employee_due_idx on "Compliance_Items" ("employee_id", "due_date");
create index if not exists payroll_employee_idx on "Payroll_Records" ("employee_id");
create index if not exists learning_employee_idx on "Learning_Milestones" ("employee_id");
create index if not exists dependencies_employee_idx on "Cross_Team_Dependencies" ("employee_id");
create index if not exists policy_evaluations_employee_idx on "policy_evaluations" ("employee_id", "evaluated_at");
create index if not exists workflow_events_execution_idx on "workflow_events" ("execution_id", "occurred_at");
create index if not exists workbench_cases_status_idx on "workbench_cases" ("status", "created_at");

-- Round 2 governance extension.  These changes are additive so the existing
-- Round 1 data and Auto table names remain intact.
alter table "policy_versions" add column if not exists "status" text not null default 'draft';
alter table "policy_versions" add column if not exists "parent_version_id" text;
alter table "policy_versions" add column if not exists "snapshot_hash" text;
alter table "policy_versions" add column if not exists "activated_at" timestamptz;
alter table "policy_versions" add column if not exists "approved_at" timestamptz;
alter table "policy_versions" add column if not exists "is_confidential_routing" boolean not null default false;

alter table "workflow_events" add column if not exists "source_event_id" text;
alter table "workflow_events" add column if not exists "sequence_no" bigint generated by default as identity;

create table if not exists "policy_simulations" (
  "simulation_id" text primary key,
  "version_id" text not null references "policy_versions"("version_id"),
  "created_at" timestamptz not null default now(),
  "created_by" text not null,
  "as_of" date not null,
  "cohort" text,
  "result" jsonb not null default '{}'::jsonb
);

create table if not exists "policy_approvals" (
  "approval_id" text primary key,
  "version_id" text not null references "policy_versions"("version_id"),
  "created_at" timestamptz not null default now(),
  "approved_by" text not null,
  "approver_role" text,
  "decision" text not null check ("decision" in ('approve', 'reject')),
  "note" text
);

create table if not exists "command_runs" (
  "command_id" text primary key,
  "created_at" timestamptz not null default now(),
  "created_by" text not null,
  "status" text not null check ("status" in ('queued', 'running', 'completed', 'failed', 'cancelled')),
  "scope" text not null check ("scope" in ('employee', 'cohort')),
  "employee_id" text,
  "cohort" text,
  "requested_reason" text,
  "auto_run_id" text,
  "last_event_at" timestamptz,
  "error_code" text,
  check (("scope" = 'employee' and "employee_id" is not null) or ("scope" = 'cohort' and "cohort" is not null))
);

alter table "command_runs" add column if not exists "workflow_key" text not null default 'hr_orchestrator';
alter table "command_runs" add column if not exists "trigger_source" text not null default 'command_center';
alter table "command_runs" add column if not exists "reconciliation_status" text not null default 'pending';
alter table "command_runs" add column if not exists "last_reconciled_at" timestamptz;
alter table "command_runs" add column if not exists "cancel_requested_at" timestamptz;
alter table "command_runs" add column if not exists "cancel_dispatched_at" timestamptz;
alter table "command_runs" add column if not exists "request_key_hash" text;
alter table "command_runs" add column if not exists "request_fingerprint" text;

create table if not exists "identity_profiles" (
  "auth_subject" text primary key,
  "employee_id" text,
  "manager_wid" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

create index if not exists policy_versions_status_idx on "policy_versions" ("status", "created_at" desc);
create index if not exists policy_simulations_version_idx on "policy_simulations" ("version_id", "created_at" desc);
create index if not exists command_runs_status_idx on "command_runs" ("status", "created_at" desc);
create index if not exists identity_profiles_employee_idx on "identity_profiles" ("employee_id");

do $$
begin
  if (select count(*) from "policy_versions" where "status" = 'active') > 1 then
    raise exception 'Migration blocked: more than one active policy version';
  end if;
  if exists (
    select 1 from "policy_approvals"
    group by "version_id", "approved_by", "approver_role" having count(*) > 1
  ) then
    raise exception 'Migration blocked: duplicate policy approvals require review';
  end if;
  if exists (
    select 1 from "command_runs" where "auto_run_id" is not null
    group by "auto_run_id" having count(*) > 1
  ) then
    raise exception 'Migration blocked: duplicate Auto run correlation requires review';
  end if;
  if exists (
    select 1 from "command_runs" where "request_key_hash" is not null
    group by "created_by", "request_key_hash" having count(*) > 1
  ) then
    raise exception 'Migration blocked: duplicate command idempotency key requires review';
  end if;
end;
$$;
create unique index if not exists policy_versions_one_active_idx on "policy_versions" (("status")) where "status" = 'active';
create unique index if not exists workflow_events_source_idx on "workflow_events" ("execution_id", "source_event_id") where "source_event_id" is not null;
create unique index if not exists workflow_events_sequence_idx on "workflow_events" ("execution_id", "sequence_no");
create unique index if not exists policy_approvals_actor_idx on "policy_approvals" ("version_id", "approved_by", "approver_role");
create unique index if not exists command_runs_request_key_idx on "command_runs" ("created_by", "request_key_hash") where "request_key_hash" is not null;
create unique index if not exists command_runs_auto_run_idx on "command_runs" ("auto_run_id") where "auto_run_id" is not null;

-- Additive checks are NOT VALID so legacy Round 1 rows do not block rollout;
-- PostgreSQL still enforces them for every new or changed Round 2 row.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'policy_versions_status_chk') then
    alter table "policy_versions" add constraint policy_versions_status_chk
      check ("status" in ('draft', 'simulated', 'approved', 'active', 'retired')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'workbench_cases_status_chk') then
    alter table "workbench_cases" add constraint workbench_cases_status_chk
      check ("status" in ('open', 'in_review', 'awaiting_external_update', 'resolved')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'workbench_cases_priority_chk') then
    alter table "workbench_cases" add constraint workbench_cases_priority_chk
      check ("priority" in ('low', 'medium', 'high', 'critical')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'command_runs_scope_exactly_one_chk') then
    alter table "command_runs" add constraint command_runs_scope_exactly_one_chk check (
      ("scope" = 'employee' and "employee_id" is not null and "cohort" is null)
      or ("scope" = 'cohort' and "cohort" is not null and "employee_id" is null)
    ) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'integration_health_status_chk') then
    alter table "integration_health" add constraint integration_health_status_chk
      check ("status" in ('healthy', 'degraded', 'down')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'confidential_cases_status_chk') then
    alter table "Confidential_Cases" add constraint confidential_cases_status_chk
      check ("status" in ('open', 'in_review', 'awaiting_external_update', 'resolved')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'workflow_events_status_chk') then
    alter table "workflow_events" add constraint workflow_events_status_chk
      check ("status" in ('queued', 'running', 'completed', 'failed', 'cancelled')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'command_runs_reconciliation_status_chk') then
    alter table "command_runs" add constraint command_runs_reconciliation_status_chk
      check ("reconciliation_status" in ('pending', 'required', 'complete')) not valid;
  end if;
end;
$$;

-- Event ledger insert and monotonic command transition are one transaction.
create or replace function public.persist_workflow_event(
  target_command_id text,
  new_event_id text,
  new_source_event_id text,
  new_event_type text,
  new_status text,
  safe_details jsonb,
  resolved_auto_run_id text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_status text;
  cancellation_requested timestamptz;
begin
  if new_status not in ('queued', 'running', 'completed', 'failed', 'cancelled') then
    raise exception 'Invalid command status';
  end if;
  select "status", "cancel_requested_at" into current_status, cancellation_requested
    from "command_runs" where "command_id" = target_command_id for update;
  if current_status is null then raise exception 'Command run not found'; end if;
  if current_status in ('completed', 'failed', 'cancelled') then return false; end if;
  if current_status = 'running' and new_status = 'queued' then return false; end if;
  if cancellation_requested is not null and new_status not in ('completed', 'failed', 'cancelled') then
    return false;
  end if;
  insert into "workflow_events" (
    "event_id", "source_event_id", "execution_id", "operator_id",
    "event_type", "status", "details"
  ) values (
    new_event_id, new_source_event_id, target_command_id, 'orchestrator',
    new_event_type, new_status, safe_details
  ) on conflict ("event_id") do nothing;
  update "command_runs" set
    "status" = new_status,
    "auto_run_id" = coalesce(resolved_auto_run_id, "auto_run_id"),
    "last_event_at" = now(),
    "reconciliation_status" = case
      when new_status in ('completed', 'failed', 'cancelled') then 'complete'
      else 'pending'
    end
  where "command_id" = target_command_id;
  return true;
end;
$$;
revoke all on function public.persist_workflow_event(text, text, text, text, text, jsonb, text) from public, anon, authenticated;
grant execute on function public.persist_workflow_event(text, text, text, text, text, jsonb, text) to service_role;

create or replace function public.claim_reconciliation_lease(
  lease_owner text,
  lease_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed boolean;
begin
  if lease_seconds < 15 or lease_seconds > 3600 then
    raise exception 'Invalid reconciliation lease duration';
  end if;
  insert into "reconciliation_leases" ("lease_key", "lease_owner", "lease_until")
    values ('auto_runs', lease_owner, now() + make_interval(secs => lease_seconds))
  on conflict ("lease_key") do update set
    "lease_owner" = excluded."lease_owner",
    "lease_until" = excluded."lease_until",
    "updated_at" = now()
  where "reconciliation_leases"."lease_until" <= now()
     or "reconciliation_leases"."lease_owner" = excluded."lease_owner"
  returning true into claimed;
  return coalesce(claimed, false);
end;
$$;
revoke all on function public.claim_reconciliation_lease(text, integer) from public, anon, authenticated;
grant execute on function public.claim_reconciliation_lease(text, integer) to service_role;

-- Case mutation and its audit entry are one transaction. The function exposes
-- no confidential payload and rejects nonexistent cases or invalid transitions.
create or replace function public.record_case_action(
  target_case_id text,
  case_table text,
  actor_subject text,
  action_decision text,
  safe_feedback text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_status text;
  current_assignee text;
  next_status text;
  resolution_identifier text := 'res_' || replace(gen_random_uuid()::text, '-', '');
begin
  if action_decision not in ('claim', 'acknowledge', 'await_external_update', 'resolve') then
    raise exception 'Unsupported case action';
  end if;
  if case_table = 'standard' then
    select "status", "assigned_to" into current_status, current_assignee
      from "workbench_cases" where "case_id" = target_case_id for update;
  elsif case_table = 'confidential' then
    select "status" into current_status from "Confidential_Cases" where "case_id" = target_case_id for update;
  else
    raise exception 'Unsupported case table';
  end if;
  if current_status is null then raise exception 'Case not found'; end if;
  if current_status = 'resolved' then raise exception 'Resolved case cannot be changed'; end if;
  if action_decision = 'claim' and current_status <> 'open' then
    raise exception 'Only an open case can be claimed';
  end if;
  if action_decision in ('acknowledge', 'await_external_update') and current_status <> 'in_review' then
    raise exception 'Case must be in review for this action';
  end if;
  if action_decision = 'resolve' and current_status not in ('in_review', 'awaiting_external_update') then
    raise exception 'Case must be reviewed before resolution';
  end if;
  if case_table = 'standard' and action_decision <> 'claim'
     and current_assignee is not null and current_assignee <> actor_subject then
    raise exception 'Case is assigned to another actor';
  end if;

  next_status := case action_decision
    when 'claim' then 'in_review'
    when 'await_external_update' then 'awaiting_external_update'
    when 'resolve' then 'resolved'
    else current_status
  end;
  if case_table = 'standard' then
    update "workbench_cases"
      set "status" = next_status,
          "assigned_to" = case when action_decision = 'claim' then actor_subject else "assigned_to" end,
          "resolved_at" = case when action_decision = 'resolve' then now() else null end
      where "case_id" = target_case_id;
  else
    update "Confidential_Cases"
      set "status" = next_status,
          "resolved_at" = case when action_decision = 'resolve' then now() else null end
      where "case_id" = target_case_id;
  end if;
  insert into "case_resolutions" ("resolution_id", "case_id", "resolved_by", "decision", "sanitized_feedback")
    values (resolution_identifier, target_case_id, actor_subject, action_decision, safe_feedback);
  return next_status;
end;
$$;
revoke all on function public.record_case_action(text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.record_case_action(text, text, text, text, text) to service_role;

-- Persisting simulation evidence and advancing draft -> simulated is atomic.
create or replace function public.record_policy_simulation(
  new_simulation_id text,
  target_version_id text,
  actor_subject text,
  evaluation_date date,
  target_cohort text,
  simulation_result jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform 1 from "policy_versions"
    where "version_id" = target_version_id and "status" = 'draft' for update;
  if not found then raise exception 'Policy must be draft before simulation'; end if;
  insert into "policy_simulations" (
    "simulation_id", "version_id", "created_by", "as_of", "cohort", "result"
  ) values (
    new_simulation_id, target_version_id, actor_subject, evaluation_date,
    target_cohort, simulation_result
  );
  update "policy_versions" set "status" = 'simulated'
    where "version_id" = target_version_id;
  insert into "policy_evaluations" (
    "evaluation_id", "policy_version_id", "policy_key", "outcome", "action", "evidence"
  ) values (
    'evaluation_' || replace(gen_random_uuid()::text, '-', ''),
    target_version_id, 'POLICY_SIMULATION', 'simulated', 'previewed',
    jsonb_build_object('simulation_id', new_simulation_id, 'as_of', evaluation_date)
  );
end;
$$;
revoke all on function public.record_policy_simulation(text, text, text, date, text, jsonb) from public, anon, authenticated;
grant execute on function public.record_policy_simulation(text, text, text, date, text, jsonb) to service_role;

-- Approval insertion and lifecycle transition are atomic. Confidential-routing
-- policies stay simulated until two independent approvers cover both roles.
create or replace function public.record_policy_approval(
  target_version_id text,
  actor_subject text,
  actor_role text,
  approval_decision text,
  approval_note text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  current_status text;
  confidential boolean;
  admin_count integer;
  confidential_count integer;
  distinct_count integer;
begin
  if actor_role not in ('admin', 'people_ops_confidential') or approval_decision not in ('approve', 'reject') then
    raise exception 'Invalid policy approval';
  end if;
  select "status", "is_confidential_routing" into current_status, confidential
    from "policy_versions" where "version_id" = target_version_id for update;
  if current_status is null then raise exception 'Policy version not found'; end if;
  if current_status <> 'simulated' then raise exception 'Policy must be simulated before approval'; end if;

  insert into "policy_approvals" ("approval_id", "version_id", "approved_by", "approver_role", "decision", "note")
    values ('approval_' || replace(gen_random_uuid()::text, '-', ''), target_version_id, actor_subject, actor_role, approval_decision, approval_note)
    on conflict ("version_id", "approved_by", "approver_role")
    do update set "decision" = excluded."decision", "note" = excluded."note", "created_at" = now();
  if approval_decision = 'reject' then return 'simulated'; end if;

  select
    count(*) filter (where "approver_role" = 'admin' and "decision" = 'approve'),
    count(*) filter (where "approver_role" = 'people_ops_confidential' and "decision" = 'approve'),
    count(distinct "approved_by") filter (where "decision" = 'approve')
  into admin_count, confidential_count, distinct_count
  from "policy_approvals" where "version_id" = target_version_id;
  if admin_count > 0 and (not confidential or (confidential_count > 0 and distinct_count > 1)) then
    update "policy_versions" set "status" = 'approved', "approved_at" = now() where "version_id" = target_version_id;
    return 'approved';
  end if;
  return 'simulated';
end;
$$;
revoke all on function public.record_policy_approval(text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.record_policy_approval(text, text, text, text, text) to service_role;

-- Atomic activation prevents operators observing a partially updated policy.
create or replace function public.activate_policy_version(target_version_id text, actor_subject text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from "policy_versions" where "version_id" = target_version_id and "status" = 'approved') then
    raise exception 'Policy version must exist and be approved before activation';
  end if;
  if not exists (select 1 from "policy_simulations" where "version_id" = target_version_id) then
    raise exception 'Policy version must be simulated before activation';
  end if;
  update "policy_versions" set "status" = 'retired' where "status" = 'active';
  update "policy_versions" set "status" = 'active', "activated_at" = now() where "version_id" = target_version_id;
  insert into "policy_evaluations" (
    "evaluation_id", "policy_version_id", "policy_key", "outcome", "action", "evidence"
  ) values (
    'evaluation_' || replace(gen_random_uuid()::text, '-', ''),
    target_version_id, 'POLICY_ACTIVATION', 'active', 'activated',
    jsonb_build_object('actor_subject', actor_subject)
  );
end;
$$;
revoke all on function public.activate_policy_version(text, text) from public, anon, authenticated;
grant execute on function public.activate_policy_version(text, text) to service_role;

-- Direct browser access is denied by default.  FastAPI and the controlled Auto
-- connection use server credentials; service-role access is still constrained
-- by backend authorization and sanitized API contracts.
do $$
declare table_name text;
begin
  foreach table_name in array array[
    'Workers', 'Manager_Directory', 'policy_config', 'Onboarding_Tasks',
    'Provisioning_Integration', 'Peakon_Engagement', 'Locations_Entities',
    'Compliance_Items', 'Payroll_Records', 'Learning_Milestones',
    'Attrition_History', 'Cross_Team_Dependencies', 'Cases_Audit_Log',
    'policy_versions', 'policy_evaluations', 'workflow_events',
    'workbench_cases', 'Confidential_Cases', 'case_resolutions',
    'integration_health', 'policy_simulations', 'policy_approvals',
    'command_runs', 'identity_profiles', 'reconciliation_leases'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end;
$$;
