-- Supabase schema for the Round 2 HR & People Ops system of record.
-- Apply to the existing Round 1 Supabase project before live seeding. Table names intentionally
-- preserve the source-system casing used by Auto and the reseeding loader.

create table if not exists "Workers" (
  "Worker_WID" text primary key,
  "Employee_ID" text unique,
  "Legal_Name" text,
  "Preferred_Name" text,
  "Business_Title" text,
  "Job_Profile" text,
  "Job_Family" text,
  "Management_Level" text,
  "Position_ID" text,
  "Manager_Name" text,
  "Manager_WID" text,
  "Cost_Center" text,
  "Location" text,
  "Hire_Date" date,
  "Worker_Type" text,
  "Time_Type" text,
  "FTE" numeric,
  "Email_Work" text,
  "jurisdiction" text,
  "time_zone" text,
  "work_auth_expiry" date,
  "cohort" text
);

-- `create table if not exists` does not add fields to an existing Round 1 table.
alter table "Workers" add column if not exists "jurisdiction" text;
alter table "Workers" add column if not exists "time_zone" text;
alter table "Workers" add column if not exists "work_auth_expiry" date;
alter table "Workers" add column if not exists "cohort" text;

create table if not exists "Manager_Directory" (
  "Manager_WID" text primary key,
  "Employee_ID" text,
  "Name" text,
  "Email_Work" text,
  "Org" text
);

create table if not exists "policy_config" (
  "field_key" text primary key,
  "category" text,
  "value" text,
  "justification" text
);

create table if not exists "Onboarding_Tasks" (
  "Event_ID" text primary key,
  "Employee_ID" text,
  "Business_Process" text,
  "Step_Name" text,
  "Milestone" text,
  "Due_Date" date,
  "Status" text,
  "Completed_Date" date,
  "Assigned_To_Role" text
);

create table if not exists "Provisioning_Integration" (
  "Integration_Event_ID" text primary key,
  "Employee_ID" text,
  "Resource" text,
  "Requested_On" date,
  "Status" text,
  "Fulfilled_On" date
);

create table if not exists "Peakon_Engagement" (
  "Response_ID" text primary key,
  "Employee_ID" text,
  "Survey_Round" text,
  "Milestone" text,
  "Driver" text,
  "Score" numeric,
  "Comment" text,
  "Submitted_At" date,
  "sentiment" text,
  "x_confidential" boolean not null default false,
  "manager_response_days" numeric
);

alter table "Peakon_Engagement" add column if not exists "sentiment" text;
alter table "Peakon_Engagement" add column if not exists "x_confidential" boolean not null default false;
alter table "Peakon_Engagement" add column if not exists "manager_response_days" numeric;

create table if not exists "Locations_Entities" (
  "entity_id" text primary key,
  "name" text,
  "country" text,
  "jurisdiction" text,
  "timezone" text
);

create table if not exists "Compliance_Items" (
  "item_id" text primary key,
  "employee_id" text,
  "doc_type" text,
  "jurisdiction" text,
  "due_date" date,
  "status" text
);

create table if not exists "Payroll_Records" (
  "payroll_id" text primary key,
  "employee_id" text,
  "cycle" text,
  "gross" numeric,
  "net" numeric,
  "status" text,
  "error_reason" text
);

create table if not exists "Learning_Milestones" (
  "milestone_id" text primary key,
  "employee_id" text,
  "course" text,
  "due_day" text,
  "status" text
);

create table if not exists "Attrition_History" (
  "record_id" text primary key,
  "job_family" text,
  "tenure_days" numeric,
  "left_flag" boolean,
  "reason" text
);

create table if not exists "Cross_Team_Dependencies" (
  "dep_id" text primary key,
  "employee_id" text,
  "team" text,
  "task" text,
  "status" text,
  "blocks_day_one" boolean not null default false
);

-- Sanitized, Auto-written audit trail. Never write a raw sensitive disclosure here.
create table if not exists "Cases_Audit_Log" (
  "case_id" text primary key,
  "timestamp" timestamptz,
  "employee_id" text,
  "case_type" text,
  "channel" text,
  "policy_rules_fired" text,
  "outcome" text
);

-- Command Center operational records. IDs are generated by the calling workflow/API so they are
-- portable across Auto and FastAPI; these tables must only contain sanitized metadata.
create table if not exists "policy_versions" (
  "version_id" text primary key,
  "created_at" timestamptz not null default now(),
  "created_by" text,
  "config_snapshot" jsonb not null,
  "change_summary" text
);

create table if not exists "policy_evaluations" (
  "evaluation_id" text primary key,
  "evaluated_at" timestamptz not null default now(),
  "execution_id" text,
  "employee_id" text,
  "policy_version_id" text,
  "policy_key" text not null,
  "outcome" text not null,
  "action" text,
  "evidence" jsonb not null default '{}'::jsonb
);

create table if not exists "workflow_events" (
  "event_id" text primary key,
  "occurred_at" timestamptz not null default now(),
  "execution_id" text,
  "employee_id" text,
  "cohort" text,
  "operator_id" text,
  "event_type" text not null,
  "status" text not null,
  "reason_codes" jsonb not null default '[]'::jsonb,
  "details" jsonb not null default '{}'::jsonb
);

create table if not exists "workbench_cases" (
  "case_id" text primary key,
  "created_at" timestamptz not null default now(),
  "employee_id" text,
  "case_type" text not null,
  "priority" text not null,
  "status" text not null default 'open',
  "recommended_action" text,
  "sanitized_context" jsonb not null default '{}'::jsonb,
  "assigned_to" text,
  "resolved_at" timestamptz
);

-- This table deliberately stores only a secure reference and minimum routing metadata. Raw pulse
-- comments must remain in the restricted Auto/Supabase confidential path, never a dashboard payload.
create table if not exists "Confidential_Cases" (
  "case_id" text primary key,
  "created_at" timestamptz not null default now(),
  "employee_id" text,
  "status" text not null default 'open',
  "secure_reference" text not null,
  "assigned_role" text not null default 'people_ops_confidential',
  "resolved_at" timestamptz
);

create table if not exists "case_resolutions" (
  "resolution_id" text primary key,
  "case_id" text not null,
  "resolved_at" timestamptz not null default now(),
  "resolved_by" text not null,
  "decision" text not null,
  "sanitized_feedback" text
);

create table if not exists "integration_health" (
  "integration_key" text primary key,
  "category" text not null,
  "status" text not null,
  "checked_at" timestamptz not null default now(),
  "last_success_at" timestamptz,
  "detail" text
);

create index if not exists workers_cohort_idx on "Workers" ("cohort");
create index if not exists onboarding_tasks_employee_idx on "Onboarding_Tasks" ("Employee_ID");
create index if not exists provisioning_employee_idx on "Provisioning_Integration" ("Employee_ID");
create index if not exists peakon_employee_idx on "Peakon_Engagement" ("Employee_ID");
create index if not exists compliance_employee_due_idx on "Compliance_Items" ("employee_id", "due_date");
create index if not exists payroll_employee_idx on "Payroll_Records" ("employee_id");
create index if not exists learning_employee_idx on "Learning_Milestones" ("employee_id");
create index if not exists dependencies_employee_idx on "Cross_Team_Dependencies" ("employee_id");
create index if not exists policy_evaluations_employee_idx on "policy_evaluations" ("employee_id", "evaluated_at");
create index if not exists workflow_events_execution_idx on "workflow_events" ("execution_id", "occurred_at");
create index if not exists workbench_cases_status_idx on "workbench_cases" ("status", "created_at");

-- Round 2 governance extension.  These changes are additive so the existing
-- Round 1 data and Auto table names remain intact.
alter table "policy_versions" add column if not exists "status" text not null default 'draft';
alter table "policy_versions" add column if not exists "parent_version_id" text;
alter table "policy_versions" add column if not exists "snapshot_hash" text;
alter table "policy_versions" add column if not exists "activated_at" timestamptz;
alter table "policy_versions" add column if not exists "approved_at" timestamptz;
alter table "policy_versions" add column if not exists "is_confidential_routing" boolean not null default false;

create table if not exists "policy_simulations" (
  "simulation_id" text primary key,
  "version_id" text not null references "policy_versions"("version_id"),
  "created_at" timestamptz not null default now(),
  "created_by" text not null,
  "as_of" date not null,
  "cohort" text,
  "result" jsonb not null default '{}'::jsonb
);

create table if not exists "policy_approvals" (
  "approval_id" text primary key,
  "version_id" text not null references "policy_versions"("version_id"),
  "created_at" timestamptz not null default now(),
  "approved_by" text not null,
  "approver_role" text,
  "decision" text not null check ("decision" in ('approve', 'reject')),
  "note" text
);

create table if not exists "command_runs" (
  "command_id" text primary key,
  "created_at" timestamptz not null default now(),
  "created_by" text not null,
  "status" text not null check ("status" in ('queued', 'running', 'completed', 'failed', 'cancelled')),
  "scope" text not null check ("scope" in ('employee', 'cohort')),
  "employee_id" text,
  "cohort" text,
  "requested_reason" text,
  "auto_run_id" text,
  "last_event_at" timestamptz,
  "error_code" text,
  check (("scope" = 'employee' and "employee_id" is not null) or ("scope" = 'cohort' and "cohort" is not null))
);

create table if not exists "identity_profiles" (
  "auth_subject" text primary key,
  "employee_id" text,
  "manager_wid" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now()
);

create index if not exists policy_versions_status_idx on "policy_versions" ("status", "created_at" desc);
create index if not exists policy_simulations_version_idx on "policy_simulations" ("version_id", "created_at" desc);
create index if not exists command_runs_status_idx on "command_runs" ("status", "created_at" desc);
create index if not exists identity_profiles_employee_idx on "identity_profiles" ("employee_id");

-- Atomic activation prevents operators observing a partially updated policy.
create or replace function public.activate_policy_version(target_version_id text, actor_subject text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from "policy_versions" where "version_id" = target_version_id and "status" = 'approved') then
    raise exception 'Policy version must exist and be approved before activation';
  end if;
  if not exists (select 1 from "policy_simulations" where "version_id" = target_version_id) then
    raise exception 'Policy version must be simulated before activation';
  end if;
  update "policy_versions" set "status" = 'retired' where "status" = 'active';
  update "policy_versions" set "status" = 'active', "activated_at" = now() where "version_id" = target_version_id;
end;
$$;
revoke all on function public.activate_policy_version(text, text) from public, anon, authenticated;
grant execute on function public.activate_policy_version(text, text) to service_role;

-- Direct browser access is denied by default.  FastAPI and the controlled Auto
-- connection use server credentials; service-role access is still constrained
-- by backend authorization and sanitized API contracts.
do $$
declare table_name text;
begin
  foreach table_name in array array[
    'Workers', 'Manager_Directory', 'policy_config', 'Onboarding_Tasks',
    'Provisioning_Integration', 'Peakon_Engagement', 'Locations_Entities',
    'Compliance_Items', 'Payroll_Records', 'Learning_Milestones',
    'Attrition_History', 'Cross_Team_Dependencies', 'Cases_Audit_Log',
    'policy_versions', 'policy_evaluations', 'workflow_events',
    'workbench_cases', 'Confidential_Cases', 'case_resolutions',
    'integration_health', 'policy_simulations', 'policy_approvals',
    'command_runs', 'identity_profiles'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end;
$$;
